name: naturinorge_guide
description: A new Flutter project.
version: 0.0.37+37
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  moor: ^4.6.1+1
  drift: ^1.7.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2
  provider: ^6.0.0
  built_collection: ^5.1.1
  built_value: ^8.1.2
  easy_localization: ^3.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_staggered_grid_view: ^0.4.0
  toggle_switch: ^1.2.0
  uuid: ^3.0.4
  url_launcher: ^6.0.10
  filter_list: ^1.0.2
  camera: ^0.9.8+1
  image: ^3.0.3
  tflite_flutter: ^0.9.0
  tflite_flutter_helper:
    git:
      url: 'https://github.com/filofan1/tflite_flutter_helper.git'
      ref: onRequestPermissionsResult-parameters
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  collection: ^1.15.0
  flutter_speed_dial: ^6.0.0
dependency_overrides:
  camera: ^0.9.8+1
dev_dependencies:
  flutter_driver:
    sdk: flutter
  drift_dev: ^1.7.1
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.2
flutter_icons:
  image_path: assets/launch_icon/ios_icon.png
  remove_alpha_ios: true
  android: true
  ios: true
  adaptive_icon_foreground: assets/launch_icon/foreground.png
  adaptive_icon_background: '#37474f'
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/launch_icon/
  - local/
