version: '3'

services:
  nin_db_build:
    build: .
    image: nin_db_build:latest
    ports:
      - "8888:8888"
    volumes:
      - ./src:/src
      - /Users/amarok/src/UIO/NIN/natur-i-norge/assets:/data/assets
      - /Users/amarok/src/UIO/NIN/natur-i-norge/scripts/species/data-prep:/data/data-prep
